version: "2"
linters:
  default: all
  disable:
    # Too strict.
    - cyclop # redundant, covered by gocyclo
    - depguard
    - exhaustruct
    - funcorder # new, too much to move around
    - nestif # redundant, covered by gocyclo
    - nlreturn
    - testpackage
    - varnamelen
    - wsl
    - wsl_v5
    - noinlineerr
  settings:
    errcheck:
      disable-default-exclusions: false
      check-type-assertions: false
      check-blank: false
      exclude-functions:
        - fmt.Fprintf
        - fmt.Fprintln
        - fmt.Fprint
    exhaustive:
      default-signifies-exhaustive: true
    funlen:
      lines: 68
      ignore-comments: true
    ireturn:
      allow:
        - anon
        - error
        - empty
        - stdlib
        - generic
        - ast\.Node$
        - types\.DateTime$
    revive:
      rules:
        - name: var-naming
          arguments: [[], [], [{ skip-package-name-checks: true }]]
  exclusions:
    generated: lax
    rules:
      - linters:
          - err113
          - funlen
          - maintidx
        path: _test\.go
    paths:
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - gci
    - gofmt
    - gofumpt
    - goimports
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
