name: 🚀 Release
on:
  push:
    # Release on semantic version tag.
    tags: ["v[0-9]+.[0-9]+.[0-9]+"]
jobs:
  release:
    name: 🚀 Release on GitHub
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4
      - name: Generate Release Notes
        id: notes
        uses: theory/changelog-version-notes-action@v0
      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          name: "Release ${{ github.ref }}"
          body_path: "${{ steps.notes.outputs.file }}"
