name: 🚀 Release
on:
  push:
    # Release on semantic version tag.
    tags: ["v[0-9]+.[0-9]+.[0-9]+"]
jobs:
  release:
    name: 🚀 Release on GitHub
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4
      - name: Generate Release Notes
        id: notes
        uses: theory/changelog-version-notes-action@v0
      - name: Create GitHub Release
        id: release
        uses: actions/create-release@v1
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          body_path: "${{ steps.notes.outputs.file }}"
